name = "tymico-notehost"
main = "src/index.ts"
compatibility_date = "2025-09-24"
workers_dev = true

routes = [
	{ pattern = "<%= domainName %>", custom_domain = true },
	{ pattern = "www.<%= domainName %>", custom_domain = true }
]
